### ISSUE TITLE
Spelling

### ISSUE THREAD

**Issue by StrangeGirlMurph** [Chicken/antti.codes#2]
Should be "**a** year".

https://github.com/Chicken/antti.codes/blob/58fa6086b7241cffce484688ef4a96461437191f/index.html#L645

Also: Really 🙄

https://github.com/Chicken/antti.codes/blob/58fa6086b7241cffce484688ef4a96461437191f/index.html#L631-L633

**Comment by Chicken** [comment]
Should have made a PR, smh making me do the work...

**Comment by StrangeGirlMurph** [comment]
I didn't want to fork and then having to do the work of deleting the repo and stuff. It's faster in total this way :)
